# Generated by Django 5.1.7 on 2025-03-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('prise', models.IntegerField(max_length=7, verbose_name='Цена')),
                ('type', models.CharField(choices=[('T', 'Инструмент'), ('BO', 'Книга'), ('BL', 'Блок')], max_length=2, verbose_name='Тип товара')),
                ('mode', models.CharField(choices=[('I', 'Indastrial Craft2'), ('T', 'Termo'), ('V', 'Ванила')], max_length=1, verbose_name='Мод')),
            ],
        ),
    ]
