# Generated by Django 5.1.7 on 2025-03-19 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_mode_basckets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basckets',
            new_name='Baskets',
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BL', 'Блок'), ('T', 'Инструмент'), ('BO', 'Книга')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
