# Generated by Django 5.1.7 on 2025-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_basckets_baskets_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskets',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('V', 'Ванила'), ('T', 'Termo'), ('I', 'Indastrial Craft2')], max_length=1, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
