# Generated by Django 5.1.7 on 2025-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('T', 'Termo'), ('V', 'Ванила'), ('I', 'Indastrial Craft2')], max_length=1, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BO', 'Книга'), ('T', 'Инструмент'), ('BL', 'Блок')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
