# Generated by Django 5.1.7 on 2025-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BO', 'Книга'), ('BL', 'Блок'), ('T', 'Инструмент')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
