# Generated by Django 5.1.7 on 2025-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_products_price_alter_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskets',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('T', 'Termo'), ('I', 'Indastrial Craft2'), ('V', 'Ванила')], max_length=1, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('T', 'Инструмент'), ('BL', 'Блок'), ('BO', 'Книга')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
