# Generated by Django 5.1.7 on 2025-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_baskets_is_purchased_alter_products_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default=None, upload_to='shop/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('T', 'Termo'), ('V', 'Ванила'), ('I', 'Indastrial Craft2')], max_length=1, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('T', 'Инструмент'), ('BO', 'Книга'), ('BL', 'Блок')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
