# Generated by Django 5.1.7 on 2025-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_products_img_alter_products_mode_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shop/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('I', 'Indastrial Craft2'), ('T', 'Termo'), ('V', 'Ванила')], max_length=1, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BO', 'Книга'), ('T', 'Инструмент'), ('BL', 'Блок')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
