# Generated by Django 5.1.7 on 2025-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_products_img_alter_products_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default=None, upload_to='shop/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('VANILA', 'Ванила'), ('T', 'Termo'), ('Industrial craft 2', 'Indastrial Craft2')], max_length=18, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BL', 'Блок'), ('BO', 'Книга'), ('T', 'Инструмент')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
