# Generated by Django 5.1.7 on 2025-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_products_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('T', 'Инструмент'), ('BO', 'Книга'), ('BL', 'Блок')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
