# Generated by Django 5.1.7 on 2025-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BO', 'Книга'), ('BL', 'Блок'), ('T', 'Инструмент')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
