# Generated by Django 5.1.7 on 2025-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('T', 'Termo'), ('Industrial craft 2', 'Indastrial Craft2'), ('VANILA', 'Ванила')], max_length=18, verbose_name='Мод'),
        ),
    ]
