# Generated by Django 5.1.7 on 2025-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_products_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('Industrial craft 2', 'Indastrial Craft2'), ('T', 'Termo'), ('VANILA', 'Ванила')], max_length=18, verbose_name='Мод'),
        ),
    ]
