# Generated by Django 5.1.7 on 2025-04-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('T', 'Инструмент'), ('BL', 'Блок'), ('BO', 'Книга')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
