# Generated by Django 5.1.7 on 2025-04-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_products_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('T', 'Termo'), ('VANILA', 'Ванила'), ('Industrial craft 2', 'Indastrial Craft2')], max_length=18, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BL', 'Блок'), ('T', 'Инструмент'), ('BO', 'Книга')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
