# Generated by Django 5.1.7 on 2025-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_products_mode_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('VANILA', 'Ванила'), ('Industrial craft 2', 'Indastrial Craft2'), ('T', 'Termo')], max_length=18, verbose_name='Мод'),
        ),
    ]
