# Generated by Django 5.1.7 on 2025-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_products_mode_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('Industrial craft 2', 'Indastrial Craft2'), ('VANILA', 'Ванила'), ('T', 'Termo')], max_length=18, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('T', 'Инструмент'), ('BO', 'Книга'), ('BL', 'Блок')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
