# Generated by Django 5.1.7 on 2025-04-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_products_mode_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('T', 'Termo'), ('VANILA', 'Ванила'), ('Industrial craft 2', 'Indastrial Craft2')], max_length=18, verbose_name='Мод'),
        ),
    ]
