# Generated by Django 5.1.7 on 2025-04-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_alter_products_mode_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('VANILA', 'Ванила'), ('T', 'Termo'), ('Industrial craft 2', 'Indastrial Craft2')], max_length=18, verbose_name='Мод'),
        ),
    ]
