# Generated by Django 5.1.7 on 2025-04-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mode',
            field=models.CharField(choices=[('T', 'Termo'), ('Industrial craft 2', 'Indastrial Craft2'), ('VANILA', 'Ванила')], max_length=18, verbose_name='Мод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('BO', 'Книга'), ('BL', 'Блок'), ('T', 'Инструмент')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
