# Generated by Django 5.1.7 on 2025-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_alter_products_mode_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('T', 'Инструмент'), ('BO', 'Книга'), ('BL', 'Блок')], max_length=2, verbose_name='Тип товара'),
        ),
    ]
