# Generated by Django 5.1.7 on 2025-03-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_email_verified_id_alter_email_verified_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_verified',
            old_name='verified',
            new_name='Isverified',
        ),
    ]
