# Generated by Django 5.1.7 on 2025-03-16 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_email_verified_user_email_verified_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_Verified',
            new_name='User_Status',
        ),
    ]
