# Generated by Django 5.1.7 on 2025-03-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_user_status_options_user_status_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_status',
            options={'verbose_name': 'статусы пользователей', 'verbose_name_plural': 'Статусы пользователей'},
        ),
    ]
