# Generated by Django 5.1.7 on 2025-04-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_user_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_status',
            name='avatar',
            field=models.ImageField(default=None, upload_to='login/avatars/'),
        ),
    ]
