# Generated by Django 5.1.7 on 2025-04-02 21:34

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_user_status_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='avatar',
            field=models.ImageField(default='login/avatars/stive.jpg', upload_to=login.models.user_avatar_directory),
        ),
    ]
