# Generated by Django 5.1.7 on 2025-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_user_status_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_status',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
