# Generated by Django 5.1.7 on 2025-04-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_user_status_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_status',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
