# Generated by Django 5.1.7 on 2025-04-23 08:59

import django.db.models.deletion
import login.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_user_status_is_moderator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='Isverified',
            field=models.BooleanField(default=False, verbose_name='Верификация почты'),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='avatar',
            field=models.ImageField(default='login/avatars/stive.jpg', upload_to=login.models.user_avatar_directory, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Статус Модератора'),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Статус Администратора'),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
