# Generated by Django 5.1.7 on 2025-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.FloatField(verbose_name='Номер правила')),
                ('crime', models.CharField(max_length=350, verbose_name='Нарушение')),
                ('punishment', models.CharField(max_length=200, verbose_name='Наказание')),
            ],
        ),
    ]
