# Generated by Django 5.1.7 on 2025-03-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
    ]
