# Generated by Django 5.1.7 on 2025-04-16 09:24

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_rules_options'),
        ('login', '0015_user_status_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='crime',
            field=models.TextField(max_length=350, verbose_name='Нарушение'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='punishment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Наказание'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(default='news/news_img.jpg', upload_to=home.models.news_img_directory)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='login.user_status')),
            ],
        ),
    ]
