# Generated by Django 5.1.7 on 2025-04-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_rules_crime_alter_rules_punishment_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новость'},
        ),
    ]
