# Generated by Django 5.1.7 on 2025-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_news_options_news_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии под новостями'},
        ),
        migrations.AlterField(
            model_name='rules',
            name='crime',
            field=models.TextField(max_length=550, verbose_name='Нарушение'),
        ),
    ]
