# Generated by Django 5.1.7 on 2025-04-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_articles_user_articles_username'),
    ]

    operations = [
    ]
