# Generated by Django 5.1.7 on 2025-04-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_rename_indexes'),
    ]

    operations = [
    ]
