# Generated by Django 5.1.7 on 2025-04-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_public_chat'),
        ('login', '0013_alter_user_status_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_chat',
            name='username',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='login.user_status'),
        ),
    ]
