# Generated by Django 5.1.7 on 2025-04-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_public_chat_username'),
        ('login', '0015_user_status_is_moderator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_chat',
            name='username',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user_status'),
        ),
        migrations.CreateModel(
            name='ForumComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Обжаловать наказание', 'Обжаловать наказание'), ('Сообщить о нарушении правил кланом/группой игроков', 'Сообщить о нарушении правил кланом/группой игроков'), ('Сообщить о нарушении правил со стороны Администрации', 'Сообщить о нарушении правил со стороны Администрации'), ('Сообщить о нарушении правил игроком', 'Сообщить о нарушении правил игроком')], max_length=52, verbose_name='Раздел форума')),
                ('question', models.TextField(max_length=600, verbose_name='Заявление')),
                ('proofs', models.CharField(max_length=600, verbose_name='Доказательства')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('defendant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='defendant', to=settings.AUTH_USER_MODEL, verbose_name='Нарушитель')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='claimant', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Жалобу на форумe',
                'verbose_name_plural': 'Жалобы с форума',
            },
        ),
        migrations.CreateModel(
            name='ForumComplaintAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=600, verbose_name='Ответ')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_complaint_user', to=settings.AUTH_USER_MODEL, verbose_name='Отвечающий')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumcomplaints', verbose_name='Жалоба')),
            ],
        ),
        migrations.CreateModel(
            name='ForumTechQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Проблемы с оплатой', 'Проблемы с оплатой'), ('Проблемы с клиентом игры', 'Проблемы с клиентом игры'), ('Проблемы с сайтом', 'Проблемы с сайтом'), ('Получить ответ на вопрос', 'Получить ответ на вопрос')], max_length=52, verbose_name='Раздел форума')),
                ('question', models.TextField(max_length=600, verbose_name='Заявление')),
                ('proofs', models.CharField(blank=True, max_length=600, verbose_name='Скриншот проблемы')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questioner', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Вопрос на форумe',
                'verbose_name_plural': 'Вопросы с форума',
            },
        ),
        migrations.CreateModel(
            name='ForumTechAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=600, verbose_name='Ответ')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tech_user', to=settings.AUTH_USER_MODEL, verbose_name='Отвечающий')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumtechquestions', verbose_name='Вопрос')),
            ],
        ),
    ]
