# Generated by Django 5.1.7 on 2025-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_forumcomplaints_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtechquestions',
            name='user',
        ),
        migrations.AlterField(
            model_name='forumcomplaints',
            name='subject',
            field=models.CharField(choices=[('Обжаловать наказание', 'Обжаловать наказание'), ('Сообщить о нарушении правил со стороны Администрации', 'Сообщить о нарушении правил со стороны Администрации'), ('Сообщить о нарушении правил игроком', 'Сообщить о нарушении правил игроком'), ('Сообщить о нарушении правил кланом/группой игроков', 'Сообщить о нарушении правил кланом/группой игроков')], max_length=52, verbose_name='Раздел форума'),
        ),
        migrations.DeleteModel(
            name='ForumTechAnswer',
        ),
        migrations.DeleteModel(
            name='ForumTechQuestions',
        ),
    ]
