# Generated by Django 5.1.7 on 2025-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_forumcomplaints_subject_forumtechquestions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtechquestions',
            name='user',
        ),
        migrations.AlterField(
            model_name='forumcomplaints',
            name='subject',
            field=models.CharField(choices=[('Сообщить о нарушении правил игроком', 'Сообщить о нарушении правил игроком'), ('Сообщить о нарушении правил кланом/группой игроков', 'Сообщить о нарушении правил кланом/группой игроков'), ('Обжаловать наказание', 'Обжаловать наказание'), ('Сообщить о нарушении правил со стороны Администрации', 'Сообщить о нарушении правил со стороны Администрации')], max_length=52, verbose_name='Раздел форума'),
        ),
        migrations.DeleteModel(
            name='ForumTechAnswer',
        ),
        migrations.DeleteModel(
            name='ForumTechQuestions',
        ),
    ]
