# Generated by Django 5.1.7 on 2025-04-09 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_forumcomplaints_subject_techquestions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechQuestions',
            new_name='ForumTechQuestions',
        ),
        migrations.AlterField(
            model_name='forumcomplaints',
            name='subject',
            field=models.CharField(choices=[('Обжаловать наказание', 'Обжаловать наказание'), ('Сообщить о нарушении правил кланом/группой игроков', 'Сообщить о нарушении правил кланом/группой игроков'), ('Сообщить о нарушении правил со стороны Администрации', 'Сообщить о нарушении правил со стороны Администрации'), ('Сообщить о нарушении правил игроком', 'Сообщить о нарушении правил игроком')], max_length=52, verbose_name='Раздел форума'),
        ),
    ]
