# Generated by Django 5.1.7 on 2025-04-16 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_rename_techquestions_forumtechquestions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumtechanswer',
            options={'verbose_name': 'Ответ на технический вопрос', 'verbose_name_plural': 'Ответы на технические вопросы'},
        ),
        migrations.AddField(
            model_name='forumcomplaintanswer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumtechanswer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumcomplaints',
            name='subject',
            field=models.CharField(choices=[('Сообщить о нарушении правил игроком', 'Сообщить о нарушении правил игроком'), ('Сообщить о нарушении правил кланом/группой игроков', 'Сообщить о нарушении правил кланом/группой игроков'), ('Сообщить о нарушении правил со стороны Администрации', 'Сообщить о нарушении правил со стороны Администрации'), ('Обжаловать наказание', 'Обжаловать наказание')], max_length=52, verbose_name='Раздел форума'),
        ),
        migrations.AlterField(
            model_name='forumtechanswer',
            name='answer',
            field=models.CharField(max_length=600, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='forumtechquestions',
            name='question',
            field=models.TextField(max_length=600, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='forumtechquestions',
            name='subject',
            field=models.CharField(choices=[('Получить ответ на вопрос', 'Получить ответ на вопрос'), ('Проблемы с сайтом', 'Проблемы с сайтом'), ('Проблемы с клиентом игры', 'Проблемы с клиентом игры'), ('Проблемы с оплатой', 'Проблемы с оплатой')], max_length=52, verbose_name='Раздел форума'),
        ),
        migrations.AlterField(
            model_name='forumtechquestions',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questioner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель тикета'),
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
