# Generated by Django 5.1.7 on 2025-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_alter_forumtechanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomplaints',
            name='subject',
            field=models.CharField(choices=[('Сообщить о нарушении правил игроком', 'Сообщить о нарушении правил игроком'), ('Обжаловать наказание', 'Обжаловать наказание'), ('Сообщить о нарушении правил со стороны Администрации', 'Сообщить о нарушении правил со стороны Администрации'), ('Сообщить о нарушении правил кланом/группой игроков', 'Сообщить о нарушении правил кланом/группой игроков')], max_length=52, verbose_name='Раздел форума'),
        ),
        migrations.AlterField(
            model_name='forumtechquestions',
            name='subject',
            field=models.CharField(choices=[('Проблемы с оплатой', 'Проблемы с оплатой'), ('Проблемы с сайтом', 'Проблемы с сайтом'), ('Проблемы с клиентом игры', 'Проблемы с клиентом игры'), ('Получить ответ на вопрос', 'Получить ответ на вопрос')], max_length=52, verbose_name='Раздел форума'),
        ),
    ]
