# Generated by Django 5.1.7 on 2025-04-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_alter_forumcomplaints_subject_and_more'),
        ('login', '0016_alter_user_status_isverified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomplaintanswer',
            options={'verbose_name': 'Ответ на жалобу', 'verbose_name_plural': 'Ответы на жалобы'},
        ),
        migrations.AlterField(
            model_name='forumcomplaintanswer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_complaint_user', to='login.user_status', verbose_name='Отвечающий'),
        ),
        migrations.AlterField(
            model_name='forumcomplaints',
            name='subject',
            field=models.CharField(choices=[('Сообщить о нарушении правил игроком', 'Сообщить о нарушении правил игроком'), ('Сообщить о нарушении правил со стороны Администрации', 'Сообщить о нарушении правил со стороны Администрации'), ('Обжаловать наказание', 'Обжаловать наказание'), ('Сообщить о нарушении правил кланом/группой игроков', 'Сообщить о нарушении правил кланом/группой игроков')], max_length=52, verbose_name='Раздел форума'),
        ),
        migrations.AlterField(
            model_name='forumtechanswer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tech_user', to='login.user_status', verbose_name='Отвечающий'),
        ),
        migrations.AlterField(
            model_name='forumtechquestions',
            name='subject',
            field=models.CharField(choices=[('Проблемы с сайтом', 'Проблемы с сайтом'), ('Проблемы с клиентом игры', 'Проблемы с клиентом игры'), ('Получить ответ на вопрос', 'Получить ответ на вопрос'), ('Проблемы с оплатой', 'Проблемы с оплатой')], max_length=52, verbose_name='Раздел форума'),
        ),
    ]
