# Generated by Django 5.1.7 on 2025-03-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articals',
            new_name='Articles',
        ),
    ]
